/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AllRouteImport } from './routes/$all'

const AllRoute = AllRouteImport.update({
  id: '/$all',
  path: '/$all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$all': typeof AllRoute
}
export interface FileRoutesByTo {
  '/$all': typeof AllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$all': typeof AllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$all'
  fileRoutesByTo: FileRoutesByTo
  to: '/$all'
  id: '__root__' | '/$all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AllRoute: typeof AllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$all': {
      id: '/$all'
      path: '/$all'
      fullPath: '/$all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AllRoute: AllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
